// Generated by gencpp from file pos_control/DoPositionControlFeedback.msg
// DO NOT EDIT!


#ifndef POS_CONTROL_MESSAGE_DOPOSITIONCONTROLFEEDBACK_H
#define POS_CONTROL_MESSAGE_DOPOSITIONCONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pos_control
{
template <class ContainerAllocator>
struct DoPositionControlFeedback_
{
  typedef DoPositionControlFeedback_<ContainerAllocator> Type;

  DoPositionControlFeedback_()
    : p_e()  {
    }
  DoPositionControlFeedback_(const ContainerAllocator& _alloc)
    : p_e(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _p_e_type;
  _p_e_type p_e;





  typedef boost::shared_ptr< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DoPositionControlFeedback_

typedef ::pos_control::DoPositionControlFeedback_<std::allocator<void> > DoPositionControlFeedback;

typedef boost::shared_ptr< ::pos_control::DoPositionControlFeedback > DoPositionControlFeedbackPtr;
typedef boost::shared_ptr< ::pos_control::DoPositionControlFeedback const> DoPositionControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pos_control::DoPositionControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pos_control::DoPositionControlFeedback_<ContainerAllocator1> & lhs, const ::pos_control::DoPositionControlFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.p_e == rhs.p_e;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pos_control::DoPositionControlFeedback_<ContainerAllocator1> & lhs, const ::pos_control::DoPositionControlFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pos_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b57fd56f43af2ea0cae1569e7c9b042";
  }

  static const char* value(const ::pos_control::DoPositionControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b57fd56f43af2eaULL;
  static const uint64_t static_value2 = 0x0cae1569e7c9b042ULL;
};

template<class ContainerAllocator>
struct DataType< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pos_control/DoPositionControlFeedback";
  }

  static const char* value(const ::pos_control::DoPositionControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Feedback\n"
"float32[] p_e   # error de posicion\n"
"\n"
"\n"
;
  }

  static const char* value(const ::pos_control::DoPositionControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p_e);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoPositionControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pos_control::DoPositionControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pos_control::DoPositionControlFeedback_<ContainerAllocator>& v)
  {
    s << indent << "p_e[]" << std::endl;
    for (size_t i = 0; i < v.p_e.size(); ++i)
    {
      s << indent << "  p_e[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.p_e[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POS_CONTROL_MESSAGE_DOPOSITIONCONTROLFEEDBACK_H
