// Generated by gencpp from file pos_control/pos_controlGoal.msg
// DO NOT EDIT!


#ifndef POS_CONTROL_MESSAGE_POS_CONTROLGOAL_H
#define POS_CONTROL_MESSAGE_POS_CONTROLGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pos_control
{
template <class ContainerAllocator>
struct pos_controlGoal_
{
  typedef pos_controlGoal_<ContainerAllocator> Type;

  pos_controlGoal_()
    : q_d(0)  {
    }
  pos_controlGoal_(const ContainerAllocator& _alloc)
    : q_d(0)  {
  (void)_alloc;
    }



   typedef int32_t _q_d_type;
  _q_d_type q_d;





  typedef boost::shared_ptr< ::pos_control::pos_controlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pos_control::pos_controlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct pos_controlGoal_

typedef ::pos_control::pos_controlGoal_<std::allocator<void> > pos_controlGoal;

typedef boost::shared_ptr< ::pos_control::pos_controlGoal > pos_controlGoalPtr;
typedef boost::shared_ptr< ::pos_control::pos_controlGoal const> pos_controlGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pos_control::pos_controlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pos_control::pos_controlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pos_control::pos_controlGoal_<ContainerAllocator1> & lhs, const ::pos_control::pos_controlGoal_<ContainerAllocator2> & rhs)
{
  return lhs.q_d == rhs.q_d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pos_control::pos_controlGoal_<ContainerAllocator1> & lhs, const ::pos_control::pos_controlGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pos_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pos_control::pos_controlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pos_control::pos_controlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_control::pos_controlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_control::pos_controlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_control::pos_controlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_control::pos_controlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pos_control::pos_controlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e6db41b299c7b625dcb77ef92b137f0";
  }

  static const char* value(const ::pos_control::pos_controlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e6db41b299c7b62ULL;
  static const uint64_t static_value2 = 0x5dcb77ef92b137f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::pos_control::pos_controlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pos_control/pos_controlGoal";
  }

  static const char* value(const ::pos_control::pos_controlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pos_control::pos_controlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Goal\n"
"int32 q_d  #posicion deseada\n"
;
  }

  static const char* value(const ::pos_control::pos_controlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pos_control::pos_controlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q_d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_controlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pos_control::pos_controlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pos_control::pos_controlGoal_<ContainerAllocator>& v)
  {
    s << indent << "q_d: ";
    Printer<int32_t>::stream(s, indent + "  ", v.q_d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POS_CONTROL_MESSAGE_POS_CONTROLGOAL_H
