// Generated by gencpp from file pos_control/pos_controlActionGoal.msg
// DO NOT EDIT!


#ifndef POS_CONTROL_MESSAGE_POS_CONTROLACTIONGOAL_H
#define POS_CONTROL_MESSAGE_POS_CONTROLACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <pos_control/pos_controlGoal.h>

namespace pos_control
{
template <class ContainerAllocator>
struct pos_controlActionGoal_
{
  typedef pos_controlActionGoal_<ContainerAllocator> Type;

  pos_controlActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  pos_controlActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::pos_control::pos_controlGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::pos_control::pos_controlActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pos_control::pos_controlActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct pos_controlActionGoal_

typedef ::pos_control::pos_controlActionGoal_<std::allocator<void> > pos_controlActionGoal;

typedef boost::shared_ptr< ::pos_control::pos_controlActionGoal > pos_controlActionGoalPtr;
typedef boost::shared_ptr< ::pos_control::pos_controlActionGoal const> pos_controlActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pos_control::pos_controlActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pos_control::pos_controlActionGoal_<ContainerAllocator1> & lhs, const ::pos_control::pos_controlActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pos_control::pos_controlActionGoal_<ContainerAllocator1> & lhs, const ::pos_control::pos_controlActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pos_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pos_control::pos_controlActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_control::pos_controlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_control::pos_controlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f832afb8eb85fde3bf7893b6269f1b96";
  }

  static const char* value(const ::pos_control::pos_controlActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf832afb8eb85fde3ULL;
  static const uint64_t static_value2 = 0xbf7893b6269f1b96ULL;
};

template<class ContainerAllocator>
struct DataType< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pos_control/pos_controlActionGoal";
  }

  static const char* value(const ::pos_control::pos_controlActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"pos_controlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pos_control/pos_controlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Goal\n"
"int32 q_d  #posicion deseada\n"
;
  }

  static const char* value(const ::pos_control::pos_controlActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_controlActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pos_control::pos_controlActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pos_control::pos_controlActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::pos_control::pos_controlGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POS_CONTROL_MESSAGE_POS_CONTROLACTIONGOAL_H
