// Auto-generated. Do not edit!

// (in-package pos_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoPositionControlFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.p_e = null;
    }
    else {
      if (initObj.hasOwnProperty('p_e')) {
        this.p_e = initObj.p_e
      }
      else {
        this.p_e = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoPositionControlFeedback
    // Serialize message field [p_e]
    bufferOffset = _arraySerializer.float32(obj.p_e, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoPositionControlFeedback
    let len;
    let data = new DoPositionControlFeedback(null);
    // Deserialize message field [p_e]
    data.p_e = _arrayDeserializer.float32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.p_e.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pos_control/DoPositionControlFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1b57fd56f43af2ea0cae1569e7c9b042';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Feedback
    float32[] p_e   # error de posicion
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoPositionControlFeedback(null);
    if (msg.p_e !== undefined) {
      resolved.p_e = msg.p_e;
    }
    else {
      resolved.p_e = []
    }

    return resolved;
    }
};

module.exports = DoPositionControlFeedback;
