// Auto-generated. Do not edit!

// (in-package pos_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoPositionControlResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.q_i = null;
    }
    else {
      if (initObj.hasOwnProperty('q_i')) {
        this.q_i = initObj.q_i
      }
      else {
        this.q_i = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoPositionControlResult
    // Serialize message field [q_i]
    bufferOffset = _serializer.int32(obj.q_i, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoPositionControlResult
    let len;
    let data = new DoPositionControlResult(null);
    // Deserialize message field [q_i]
    data.q_i = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pos_control/DoPositionControlResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e5341c5ed66755df540250f4f2a1279a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Result
    int32 q_i   #posicion actual
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoPositionControlResult(null);
    if (msg.q_i !== undefined) {
      resolved.q_i = msg.q_i;
    }
    else {
      resolved.q_i = 0
    }

    return resolved;
    }
};

module.exports = DoPositionControlResult;
