// Auto-generated. Do not edit!

// (in-package pos_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoPositionControlGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.p_d = null;
    }
    else {
      if (initObj.hasOwnProperty('p_d')) {
        this.p_d = initObj.p_d
      }
      else {
        this.p_d = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoPositionControlGoal
    // Serialize message field [p_d]
    bufferOffset = _arraySerializer.float32(obj.p_d, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoPositionControlGoal
    let len;
    let data = new DoPositionControlGoal(null);
    // Deserialize message field [p_d]
    data.p_d = _arrayDeserializer.float32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.p_d.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pos_control/DoPositionControlGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e418e65448f8cc2bce650f74cefb1e11';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Goal
    float32[] p_d  #posicion deseada
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoPositionControlGoal(null);
    if (msg.p_d !== undefined) {
      resolved.p_d = msg.p_d;
    }
    else {
      resolved.p_d = []
    }

    return resolved;
    }
};

module.exports = DoPositionControlGoal;
