// Auto-generated. Do not edit!

// (in-package pos_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoPositionControlResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.p_i = null;
    }
    else {
      if (initObj.hasOwnProperty('p_i')) {
        this.p_i = initObj.p_i
      }
      else {
        this.p_i = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoPositionControlResult
    // Serialize message field [p_i]
    bufferOffset = _arraySerializer.float32(obj.p_i, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoPositionControlResult
    let len;
    let data = new DoPositionControlResult(null);
    // Deserialize message field [p_i]
    data.p_i = _arrayDeserializer.float32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.p_i.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pos_control/DoPositionControlResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e771ef082d91116266f80125fe749ce3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Result
    float32[] p_i   #posicion actual
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoPositionControlResult(null);
    if (msg.p_i !== undefined) {
      resolved.p_i = msg.p_i;
    }
    else {
      resolved.p_i = []
    }

    return resolved;
    }
};

module.exports = DoPositionControlResult;
