// Auto-generated. Do not edit!

// (in-package pos_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoPositionControlFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.q_e = null;
    }
    else {
      if (initObj.hasOwnProperty('q_e')) {
        this.q_e = initObj.q_e
      }
      else {
        this.q_e = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoPositionControlFeedback
    // Serialize message field [q_e]
    bufferOffset = _serializer.int32(obj.q_e, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoPositionControlFeedback
    let len;
    let data = new DoPositionControlFeedback(null);
    // Deserialize message field [q_e]
    data.q_e = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pos_control/DoPositionControlFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5d324708c1e984101536f9f48e03da54';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Feedback
    int32 q_e   # error de posicion
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoPositionControlFeedback(null);
    if (msg.q_e !== undefined) {
      resolved.q_e = msg.q_e;
    }
    else {
      resolved.q_e = 0
    }

    return resolved;
    }
};

module.exports = DoPositionControlFeedback;
