; Auto-generated. Do not edit!


(cl:in-package pos_control-msg)


;//! \htmlinclude DoPositionControlResult.msg.html

(cl:defclass <DoPositionControlResult> (roslisp-msg-protocol:ros-message)
  ((q_i
    :reader q_i
    :initarg :q_i
    :type cl:integer
    :initform 0))
)

(cl:defclass DoPositionControlResult (<DoPositionControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoPositionControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoPositionControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pos_control-msg:<DoPositionControlResult> is deprecated: use pos_control-msg:DoPositionControlResult instead.")))

(cl:ensure-generic-function 'q_i-val :lambda-list '(m))
(cl:defmethod q_i-val ((m <DoPositionControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pos_control-msg:q_i-val is deprecated.  Use pos_control-msg:q_i instead.")
  (q_i m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoPositionControlResult>) ostream)
  "Serializes a message object of type '<DoPositionControlResult>"
  (cl:let* ((signed (cl:slot-value msg 'q_i)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoPositionControlResult>) istream)
  "Deserializes a message object of type '<DoPositionControlResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'q_i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoPositionControlResult>)))
  "Returns string type for a message object of type '<DoPositionControlResult>"
  "pos_control/DoPositionControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoPositionControlResult)))
  "Returns string type for a message object of type 'DoPositionControlResult"
  "pos_control/DoPositionControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoPositionControlResult>)))
  "Returns md5sum for a message object of type '<DoPositionControlResult>"
  "e5341c5ed66755df540250f4f2a1279a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoPositionControlResult)))
  "Returns md5sum for a message object of type 'DoPositionControlResult"
  "e5341c5ed66755df540250f4f2a1279a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoPositionControlResult>)))
  "Returns full string definition for message of type '<DoPositionControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%int32 q_i   #posicion actual~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoPositionControlResult)))
  "Returns full string definition for message of type 'DoPositionControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%int32 q_i   #posicion actual~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoPositionControlResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoPositionControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DoPositionControlResult
    (cl:cons ':q_i (q_i msg))
))
