; Auto-generated. Do not edit!


(cl:in-package pos_control-msg)


;//! \htmlinclude DoPositionControlGoal.msg.html

(cl:defclass <DoPositionControlGoal> (roslisp-msg-protocol:ros-message)
  ((p_d
    :reader p_d
    :initarg :p_d
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass DoPositionControlGoal (<DoPositionControlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoPositionControlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoPositionControlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pos_control-msg:<DoPositionControlGoal> is deprecated: use pos_control-msg:DoPositionControlGoal instead.")))

(cl:ensure-generic-function 'p_d-val :lambda-list '(m))
(cl:defmethod p_d-val ((m <DoPositionControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pos_control-msg:p_d-val is deprecated.  Use pos_control-msg:p_d instead.")
  (p_d m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoPositionControlGoal>) ostream)
  "Serializes a message object of type '<DoPositionControlGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'p_d))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'p_d))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoPositionControlGoal>) istream)
  "Deserializes a message object of type '<DoPositionControlGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'p_d) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'p_d)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoPositionControlGoal>)))
  "Returns string type for a message object of type '<DoPositionControlGoal>"
  "pos_control/DoPositionControlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoPositionControlGoal)))
  "Returns string type for a message object of type 'DoPositionControlGoal"
  "pos_control/DoPositionControlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoPositionControlGoal>)))
  "Returns md5sum for a message object of type '<DoPositionControlGoal>"
  "e418e65448f8cc2bce650f74cefb1e11")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoPositionControlGoal)))
  "Returns md5sum for a message object of type 'DoPositionControlGoal"
  "e418e65448f8cc2bce650f74cefb1e11")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoPositionControlGoal>)))
  "Returns full string definition for message of type '<DoPositionControlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%float32[] p_d  #posicion deseada~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoPositionControlGoal)))
  "Returns full string definition for message of type 'DoPositionControlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%float32[] p_d  #posicion deseada~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoPositionControlGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'p_d) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoPositionControlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoPositionControlGoal
    (cl:cons ':p_d (p_d msg))
))
