; Auto-generated. Do not edit!


(cl:in-package pos_control-msg)


;//! \htmlinclude DoPositionControlResult.msg.html

(cl:defclass <DoPositionControlResult> (roslisp-msg-protocol:ros-message)
  ((p_i
    :reader p_i
    :initarg :p_i
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass DoPositionControlResult (<DoPositionControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoPositionControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoPositionControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pos_control-msg:<DoPositionControlResult> is deprecated: use pos_control-msg:DoPositionControlResult instead.")))

(cl:ensure-generic-function 'p_i-val :lambda-list '(m))
(cl:defmethod p_i-val ((m <DoPositionControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pos_control-msg:p_i-val is deprecated.  Use pos_control-msg:p_i instead.")
  (p_i m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoPositionControlResult>) ostream)
  "Serializes a message object of type '<DoPositionControlResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'p_i))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'p_i))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoPositionControlResult>) istream)
  "Deserializes a message object of type '<DoPositionControlResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'p_i) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'p_i)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoPositionControlResult>)))
  "Returns string type for a message object of type '<DoPositionControlResult>"
  "pos_control/DoPositionControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoPositionControlResult)))
  "Returns string type for a message object of type 'DoPositionControlResult"
  "pos_control/DoPositionControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoPositionControlResult>)))
  "Returns md5sum for a message object of type '<DoPositionControlResult>"
  "e771ef082d91116266f80125fe749ce3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoPositionControlResult)))
  "Returns md5sum for a message object of type 'DoPositionControlResult"
  "e771ef082d91116266f80125fe749ce3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoPositionControlResult>)))
  "Returns full string definition for message of type '<DoPositionControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%float32[] p_i   #posicion actual~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoPositionControlResult)))
  "Returns full string definition for message of type 'DoPositionControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%float32[] p_i   #posicion actual~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoPositionControlResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'p_i) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoPositionControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DoPositionControlResult
    (cl:cons ':p_i (p_i msg))
))
