; Auto-generated. Do not edit!


(cl:in-package pos_control-msg)


;//! \htmlinclude DoPositionControlFeedback.msg.html

(cl:defclass <DoPositionControlFeedback> (roslisp-msg-protocol:ros-message)
  ((q_e
    :reader q_e
    :initarg :q_e
    :type cl:integer
    :initform 0))
)

(cl:defclass DoPositionControlFeedback (<DoPositionControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoPositionControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoPositionControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pos_control-msg:<DoPositionControlFeedback> is deprecated: use pos_control-msg:DoPositionControlFeedback instead.")))

(cl:ensure-generic-function 'q_e-val :lambda-list '(m))
(cl:defmethod q_e-val ((m <DoPositionControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pos_control-msg:q_e-val is deprecated.  Use pos_control-msg:q_e instead.")
  (q_e m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoPositionControlFeedback>) ostream)
  "Serializes a message object of type '<DoPositionControlFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'q_e)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoPositionControlFeedback>) istream)
  "Deserializes a message object of type '<DoPositionControlFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'q_e) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoPositionControlFeedback>)))
  "Returns string type for a message object of type '<DoPositionControlFeedback>"
  "pos_control/DoPositionControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoPositionControlFeedback)))
  "Returns string type for a message object of type 'DoPositionControlFeedback"
  "pos_control/DoPositionControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoPositionControlFeedback>)))
  "Returns md5sum for a message object of type '<DoPositionControlFeedback>"
  "5d324708c1e984101536f9f48e03da54")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoPositionControlFeedback)))
  "Returns md5sum for a message object of type 'DoPositionControlFeedback"
  "5d324708c1e984101536f9f48e03da54")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoPositionControlFeedback>)))
  "Returns full string definition for message of type '<DoPositionControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback~%int32 q_e   # error de posicion~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoPositionControlFeedback)))
  "Returns full string definition for message of type 'DoPositionControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback~%int32 q_e   # error de posicion~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoPositionControlFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoPositionControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DoPositionControlFeedback
    (cl:cons ':q_e (q_e msg))
))
