; Auto-generated. Do not edit!


(cl:in-package pos_control-msg)


;//! \htmlinclude pos_controlGoal.msg.html

(cl:defclass <pos_controlGoal> (roslisp-msg-protocol:ros-message)
  ((q_d
    :reader q_d
    :initarg :q_d
    :type cl:integer
    :initform 0))
)

(cl:defclass pos_controlGoal (<pos_controlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pos_controlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pos_controlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pos_control-msg:<pos_controlGoal> is deprecated: use pos_control-msg:pos_controlGoal instead.")))

(cl:ensure-generic-function 'q_d-val :lambda-list '(m))
(cl:defmethod q_d-val ((m <pos_controlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pos_control-msg:q_d-val is deprecated.  Use pos_control-msg:q_d instead.")
  (q_d m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pos_controlGoal>) ostream)
  "Serializes a message object of type '<pos_controlGoal>"
  (cl:let* ((signed (cl:slot-value msg 'q_d)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pos_controlGoal>) istream)
  "Deserializes a message object of type '<pos_controlGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'q_d) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pos_controlGoal>)))
  "Returns string type for a message object of type '<pos_controlGoal>"
  "pos_control/pos_controlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pos_controlGoal)))
  "Returns string type for a message object of type 'pos_controlGoal"
  "pos_control/pos_controlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pos_controlGoal>)))
  "Returns md5sum for a message object of type '<pos_controlGoal>"
  "5e6db41b299c7b625dcb77ef92b137f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pos_controlGoal)))
  "Returns md5sum for a message object of type 'pos_controlGoal"
  "5e6db41b299c7b625dcb77ef92b137f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pos_controlGoal>)))
  "Returns full string definition for message of type '<pos_controlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%int32 q_d  #posicion deseada~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pos_controlGoal)))
  "Returns full string definition for message of type 'pos_controlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%int32 q_d  #posicion deseada~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pos_controlGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pos_controlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'pos_controlGoal
    (cl:cons ':q_d (q_d msg))
))
