; Auto-generated. Do not edit!


(cl:in-package pos_control-msg)


;//! \htmlinclude pos_controlFeedback.msg.html

(cl:defclass <pos_controlFeedback> (roslisp-msg-protocol:ros-message)
  ((q_e
    :reader q_e
    :initarg :q_e
    :type cl:integer
    :initform 0))
)

(cl:defclass pos_controlFeedback (<pos_controlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pos_controlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pos_controlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pos_control-msg:<pos_controlFeedback> is deprecated: use pos_control-msg:pos_controlFeedback instead.")))

(cl:ensure-generic-function 'q_e-val :lambda-list '(m))
(cl:defmethod q_e-val ((m <pos_controlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pos_control-msg:q_e-val is deprecated.  Use pos_control-msg:q_e instead.")
  (q_e m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pos_controlFeedback>) ostream)
  "Serializes a message object of type '<pos_controlFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'q_e)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pos_controlFeedback>) istream)
  "Deserializes a message object of type '<pos_controlFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'q_e) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pos_controlFeedback>)))
  "Returns string type for a message object of type '<pos_controlFeedback>"
  "pos_control/pos_controlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pos_controlFeedback)))
  "Returns string type for a message object of type 'pos_controlFeedback"
  "pos_control/pos_controlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pos_controlFeedback>)))
  "Returns md5sum for a message object of type '<pos_controlFeedback>"
  "5d324708c1e984101536f9f48e03da54")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pos_controlFeedback)))
  "Returns md5sum for a message object of type 'pos_controlFeedback"
  "5d324708c1e984101536f9f48e03da54")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pos_controlFeedback>)))
  "Returns full string definition for message of type '<pos_controlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback~%int32 q_e   # error de posicion~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pos_controlFeedback)))
  "Returns full string definition for message of type 'pos_controlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback~%int32 q_e   # error de posicion~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pos_controlFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pos_controlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'pos_controlFeedback
    (cl:cons ':q_e (q_e msg))
))
